dist: trusty
sudo: required

language: node_js
node_js:
- "8"

matrix:
  include:
  - os: osx
  - os: linux
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
    - sudo apt-get install --no-install-recommends -y rpm

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm run electron:build

branches:
  only:
  - master
